name = "ParallelMergeCSR"
uuid = "c4b929cc-6141-4ba4-8849-280a863346e1"
authors = ["Phillip Weinberg <pweinberg@quera.com>", "John Long <jlong@quera.com>"]
version = "1.0.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Polyester = "0.7.2"
julia = "1.8"

[extras]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
