name: CI
# execute on a push or pull request
on:
  - push
  - pull_request

jobs:
  pre_job: 
    runs-on: [ubuntu-latest]
    # taken from Bloqade.jl CI.yaml
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths_ignore: '["**/README.md"]'

  # taken from example on julia-actions/runtest@v1
  test:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    strategy:
      matrix:
        julia-num-threads: [1,2,4,8]
        julia-version: ['1.8']
        julia-arch: [x64]
        os: [ubuntu-latest]
    #1, 2, 4, 8 thread test
    name: Threads - ${{matrix.julia-num-threads}}
    env:
      JULIA_NUM_THREADS: ${{ matrix.julia-num-threads }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: "Setup Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - name: "Confirm Number of Threads"
        run: julia -e 'println(Threads.nthreads())'
      - uses: julia-actions/julia-buildpkg@v1
      - name: "Run Tests"
        uses: julia-actions/julia-runtest@v1
        # Only get code coverage and tests ONCE
      - name: "Process Coverage"
        if: ${{matrix.julia-num-threads == 8}}
        uses: julia-actions/julia-processcoverage@v1
      - name: "Submit to codecov"
        if: ${{matrix.julia-num-threads == 8}}
        uses: julia-actions/codecov-action@v3
        with:
          files: lcov.info